[package]
name = "rust_kifuwarabe_shell_visualizer"
version = "0.1.0"
authors = ["むずでょ <muzudho1@gmail.com>"]

[dependencies]
serde_json = "1.0"

[dependencies.kifuwarabe_shell]
git = "https://github.com/muzudho/rust_kifuwarabe_shell.git"
rev = "a76864c2beb7c58f0e185c263eda47b20f8df7c9"
